### ISSUE TITLE
custom filename

### ISSUE THREAD

**Issue by huzaifamk** [ozaytsev86/create-env-file-action#1]
Hey ozaytsev86, I would like to ask the format of adding a custom filename other than .env , does the below format looks good or need some changes?

- name: Create .txt secret file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_AES_KEY: ${{ secrets.AES_KEY }} # The secret value to write to the file
          file-name: aes-key.txt # The name of the file to write to

It will be great if you help me out in this 👍 : )

**Comment by ozaytsev86** [comment]
hey @HuzaifaMk , I just checked the code and it should work, in case of any problem, please let me know and I will give you a hand with it ;)

**Comment by huzaifamk** [comment]
Thanks alot @ozaytsev86 for support 👍 💯 
This action is very useful! Thank you!
