### ISSUE TITLE
The following actions use a deprecated Node.js version and will be forced to run on node20: ozaytsev86/create-env-file@v1.

### ISSUE THREAD

**Issue by martijnhartlief** [ozaytsev86/create-env-file-action#6]
> The following actions use a deprecated Node.js version and will be forced to run on node20: ozaytsev86/create-env-file@v1. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

I don't know if it causes any issues on node20, but I felt like I should mention it.

**Comment by ozaytsev86** [comment]
Hi @martijnhartlief, thanks for mentioning it, I will take a look. Probably I will have to update it as it was long time without bumping node version.

**Comment by ozaytsev86** [comment]
Hi @martijnhartlief, I've updated the action to support Node.js 20 and also changed the versioning to semanctic :) Thank you for raising this.
